# Generated by Django 5.0 on 2023-12-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0002_pokemoncard_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemoncard',
            name='image_url',
        ),
    ]
